### ISSUE TITLE
create UIS

### ISSUE THREAD

**Issue by vima08** [vima08/ViseFrontEnd#2]
https://en.wikipedia.org/wiki/User_interface_specification
https://habrahabr.ru/company/aiken/blog/129653/
https://gomockingbird.com/home

Создать мокапы страниц
- эксперимент
- поиск
- результаты

**Comment by vima08** [comment]
@Angotic, please attach your mockup and close the issue

**Comment by Angotic** [comment]
https://gomockingbird.com/projects/09egr72/4gXVnC
